version: 2.1

defaults: &defaults
  working_directory: ~/repo
  docker:
    # Built from:
    # https://github.com/pyodide/pyodide/blob/2ab4b0ab6aefe99fd994bb4f9ab086e5c0aebb7b/Dockerfile
    - image: pyodide/pyodide-env:20230126-chrome109-firefox109-py311
  environment:
    - EMSDK_NUM_CORES: 3
      EMCC_CORES: 3

jobs:
  install-emsdk:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: install emsdk
          no_output_timeout: 1200
          command: |
            git clone https://github.com/emscripten-core/emsdk.git --depth=1
            cd emsdk
            ./emsdk install 3.1.30
            ./emsdk activate 3.1.30

      - persist_to_workspace:
          root: .
          paths:
            - emsdk

  build-libffi:
    parameters:
      wasm-bigint:
        description: Should we build with wasm-bigint?
        type: string
        default: ""
    environment:
      WASM_BIGINT: << parameters.wasm-bigint >>
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: .

      - run:
          name: build
          command: |
            source ./emsdk/emsdk_env.sh
            ./testsuite/emscripten/build.sh

      - run:
          name: build tests
          command: |
            source ./emsdk/emsdk_env.sh
            cp -r testsuite/libffi.call testsuite/libffi.call.test
            cp -r testsuite/libffi.closures testsuite/libffi.closures.test
            ./testsuite/emscripten/build-tests.sh testsuite/libffi.call.test
            ./testsuite/emscripten/build-tests.sh testsuite/libffi.closures.test

      - persist_to_workspace:
          root: .
          paths:
            - target
            - testsuite

  test-firefox:
    <<: *defaults
    steps:
      - checkout

      - attach_workspace:
          at: .

      - run:
          name: run tests
          no_output_timeout: 1200
          command: |
            git reset --hard
            cd testsuite/emscripten/
            mkdir test-results
            pytest --junitxml=test-results/junit.xml -k firefox test_libffi.py
      - store_test_results:
          path: testsuite/emscripten/test-results

  test-chrome:
    <<: *defaults
    steps:
      - checkout

      - attach_workspace:
          at: .

      - run:
          name: run tests
          no_output_timeout: 1200
          command: |
            git reset --hard
            cd testsuite/emscripten/
            mkdir test-results
            pytest --junitxml=test-results/junit.xml -k chrome test_libffi.py
      - store_test_results:
          path: testsuite/emscripten/test-results

  test-firefox-bigint:
    <<: *defaults
    steps:
      - checkout

      - attach_workspace:
          at: .

      - run:
          name: run tests
          no_output_timeout: 1200
          command: |
            git reset --hard
            cd testsuite/emscripten/
            mkdir test-results
            pytest --junitxml=test-results/junit.xml -k firefox test_libffi.py
      - store_test_results:
          path: testsuite/emscripten/test-results

  test-chrome-bigint:
    <<: *defaults
    steps:
      - checkout

      - attach_workspace:
          at: .

      - run:
          name: run tests
          no_output_timeout: 1200
          command: |
            git reset --hard
            cd testsuite/emscripten/
            mkdir test-results
            pytest --junitxml=test-results/junit.xml -k chrome test_libffi.py
      - store_test_results:
          path: testsuite/emscripten/test-results

  test-node:
    <<: *defaults
    steps:
      - checkout

      - attach_workspace:
          at: .

      - run:
          name: run tests
          no_output_timeout: 1200
          command: |
            source ./emsdk/emsdk_env.sh
            rm testsuite/libffi.go/go.exp
            testsuite/emscripten/node-tests.sh

  test-node-bigint:
    <<: *defaults
    steps:
      - checkout

      - attach_workspace:
          at: .

      - run:
          name: run tests
          no_output_timeout: 1200
          command: |
            source ./emsdk/emsdk_env.sh
            rm testsuite/libffi.go/go.exp
            testsuite/emscripten/node-tests.sh --enable-wasm-bigint

workflows:
  version: 2
  build-and-test:
    jobs:
      - install-emsdk

      - build-libffi:
          name: build-libffi
          requires:
            - install-emsdk

      - build-libffi:
          name: build-libffi-bigint
          wasm-bigint: "true"
          requires:
            - install-emsdk

      - test-firefox:
          requires:
            - build-libffi
      - test-chrome:
          requires:
            - build-libffi

      - test-firefox-bigint:
          requires:
            - build-libffi-bigint
      - test-chrome-bigint:
          requires:
            - build-libffi-bigint

      - test-node:
          requires:
            - install-emsdk
      - test-node-bigint:
          requires:
            - install-emsdk
